version: '3.8'

services:
  paddleocr-server:
    build: .
    container_name: paddleocr-optimized
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - paddleocr-models:/root/.paddleocr
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  paddleocr-models:
    driver: local